[workspace]
members = ["crates/*", "tests"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.4.0-beta-dev.12"
hdk = "=0.3.0-beta-dev.16"
serde = "=1.0.166"
holochain = "=0.3.0-beta-dev.20"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
