[workspace]
members = ["crates/*", "tests"]
resolver = "2"

[workspace.dependencies]
hdi = "0.3.3-beta-rc.0"
hdk = "0.2.3-beta-rc.0"
serde = "1"
holochain = "0.2.3-beta-rc.1"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
