[workspace]
members = ["crates/*", "tests"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.3.1-beta-dev.0"
hdk = "=0.2.1-beta-dev.0"
serde = "1"
holochain = {git = "https://github.com/holochain/holochain", branch="develop"}

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
