[workspace]
members = ["crates/*", "tests"]
resolver = "2"

[workspace.dependencies]
hdi = "0.2.0-beta-rc.3"
hdk = "0.1.0-beta-rc.3"
serde = "1"
holochain = "0.1.0-beta-rc.4"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
